server.port=${SERVER_PORT:8081}
spring.application.name=usuarios

# MariaDB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/streaming_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:changeme_demo}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.open-in-view=false

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
